In [1]:
import numpy as np
import pandas as pd

In [2]:
ser1=pd.Series([100,200,300],['xx','yy','zz']) #series

In [3]:
ser1

xx    100
yy    200
zz    300
dtype: int64

In [4]:
ser1['xx']

np.int64(100)

In [5]:
ser1.iloc[1].item()

200

In [6]:
ser1.iloc[2]

np.int64(300)

In [7]:
ser1.index

Index(['xx', 'yy', 'zz'], dtype='str')

In [8]:
d={'one':pd.Series([100,200,300],index=['apple','ball','clock']),
   'two':pd.Series([111,222,333,4444],index=['apple','ball','ceril','dancy'])}

In [9]:
d

{'one': apple    100
 ball     200
 clock    300
 dtype: int64,
 'two': apple     111
 ball      222
 ceril     333
 dancy    4444
 dtype: int64}

In [10]:
df=pd.DataFrame(d)
df

         one     two
apple  100.0   111.0
ball   200.0   222.0
ceril    NaN   333.0
clock  300.0     NaN
dancy    NaN  4444.0

In [11]:
df['one']

apple    100.0
ball     200.0
ceril      NaN
clock    300.0
dancy      NaN
Name: one, dtype: float64

In [12]:
df['one']['ball']

np.float64(200.0)

In [13]:
df['three']=df['one']=df['two']

In [14]:
df

          one     two   three
apple   111.0   111.0   111.0
ball    222.0   222.0   222.0
ceril   333.0   333.0   333.0
clock     NaN     NaN     NaN
dancy  4444.0  4444.0  4444.0

In [15]:
df.insert(1,'copy_of_one',df['one'])
df

          one  copy_of_one     two   three
apple   111.0        111.0   111.0   111.0
ball    222.0        222.0   222.0   222.0
ceril   333.0        333.0   333.0   333.0
clock     NaN          NaN     NaN     NaN
dancy  4444.0       4444.0  4444.0  4444.0

In [16]:
df['one_lower_half']=df['one'][:2]
df

          one  copy_of_one     two   three  one_lower_half
apple   111.0        111.0   111.0   111.0           111.0
ball    222.0        222.0   222.0   222.0           222.0
ceril   333.0        333.0   333.0   333.0             NaN
clock     NaN          NaN     NaN     NaN             NaN
dancy  4444.0       4444.0  4444.0  4444.0             NaN

In [17]:
df['filet1']=(df['two']%2==0)
df

          one  copy_of_one     two   three  one_lower_half  filet1
apple   111.0        111.0   111.0   111.0           111.0   False
ball    222.0        222.0   222.0   222.0           222.0    True
ceril   333.0        333.0   333.0   333.0             NaN   False
clock     NaN          NaN     NaN     NaN             NaN   False
dancy  4444.0       4444.0  4444.0  4444.0             NaN    True

In [18]:
import os

In [19]:
os.chdir("C:\\Users\\ASUS\\Downloads\\ml-latest-small\\ml-latest-small")

In [20]:
movies=pd.read_csv('movies.csv')

In [21]:
movies.head(10)

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy
5,6,Heat (1995),Action|Crime|Thriller
6,7,Sabrina (1995),Comedy|Romance
7,8,Tom and Huck (1995),Adventure|Children
8,9,Sudden Death (1995),Action
9,10,GoldenEye (1995),Action|Adventure|Thriller

In [22]:
ratings=pd.read_csv('ratings.csv')

In [23]:
ratings.head()

   userId  movieId  rating  timestamp
0       1        1     4.0  964982703
1       1        3     4.0  964981247
2       1        6     4.0  964982224
3       1       47     5.0  964983815
4       1       50     5.0  964982931

In [24]:
tags=pd.read_csv('tags.csv')

In [25]:
tags.head()

   userId  movieId              tag   timestamp
0       2    60756            funny  1445714994
1       2    60756  Highly quotable  1445714996
2       2    60756     will ferrell  1445714992
3       2    89774     Boxing story  1445715207
4       2    89774              MMA  1445715200

In [26]:
movies.info()

<class 'pandas.DataFrame'>
RangeIndex: 9742 entries, 0 to 9741
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   movieId  9742 non-null   int64
 1   title    9742 non-null   str
 2   genres   9742 non-null   str
dtypes: int64(1), str(2)
memory usage: 626.1 KB

In [27]:
ratings.info()

<class 'pandas.DataFrame'>
RangeIndex: 100836 entries, 0 to 100835
Data columns (total 4 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   userId     100836 non-null  int64
 1   movieId    100836 non-null  int64
 2   rating     100836 non-null  float64
 3   timestamp  100836 non-null  int64
dtypes: float64(1), int64(3)
memory usage: 3.1 MB

In [28]:
ratings.describe()

              userId        movieId         rating     timestamp
count  100836.000000  100836.000000  100836.000000  1.008360e+05
mean      326.127564   19435.295718       3.501557  1.205946e+09
std       182.618491   35530.987199       1.042529  2.162610e+08
min         1.000000       1.000000       0.500000  8.281246e+08
25%       177.000000    1199.000000       3.000000  1.019124e+09
50%       325.000000    2991.000000       3.500000  1.186087e+09
75%       477.000000    8122.000000       4.000000  1.435994e+09
max       610.000000  193609.000000       5.000000  1.537799e+09

In [29]:
ratings['rating'].mean()

np.float64(3.501556983616962)

In [30]:
ratings['rating'].max()

5.0

In [31]:
ratings['rating'].mean()

np.float64(3.501556983616962)

In [32]:
is_highly_rated=ratings['rating']>=5.0

In [33]:
ratings[is_highly_rated]

        userId  movieId  rating   timestamp
3            1       47     5.0   964983815
4            1       50     5.0   964982931
6            1      101     5.0   964980868
8            1      151     5.0   964984041
9            1      157     5.0   964984100
...        ...      ...     ...         ...
100814     610   158238     5.0  1479545219
100829     610   164179     5.0  1493845631
100832     610   168248     5.0  1493850091
100833     610   168250     5.0  1494273047
100834     610   168252     5.0  1493846352

[13211 rows x 4 columns]

In [34]:
avg_rating=ratings[['movieId','rating']].groupby('movieId').mean()

In [35]:
avg_rating.head()

           rating
movieId
1        3.920930
2        3.431818
3        3.259615
4        2.357143
5        3.071429

In [36]:
avg_rating=ratings[['movieId','rating']].groupby('movieId').count()
avg_rating.head()

         rating
movieId
1           215
2           110
3            52
4             7
5            49

In [37]:
t=movies.merge(ratings,on='movieId',how='inner')

In [38]:
t

,movieId,title,genres,userId,rating,timestamp
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,1,4.0,964982703
1,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,5,4.0,847434962
2,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,7,4.5,1106635946
3,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,15,2.5,1510577970
4,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,17,4.5,1305696483
...,...,...,...,...,...,...
100831,193581,Black Butler: Book of the Atlantic (2017),Action|Animation|Comedy|Fantasy,184,4.0,1537109082
100832,193583,No Game No Life: Zero (2017),Animation|Comedy|Fantasy,184,3.5,1537109545
100833,193585,Flint (2017),Drama,184,3.5,1537109805
100834,193587,Bungo Stray Dogs: Dead Apple (2018),Action|Animation,184,3.5,1537110021
100835,193609,Andrew Dice Clay: Dice Rules (1991),Comedy,331,4.0,1537157606

In [39]:
t1=movies.merge(ratings,on='movieId',how='left')
t1

,movieId,title,genres,userId,rating,timestamp
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,1.0,4.0,9.649827e+08
1,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,5.0,4.0,8.474350e+08
2,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,7.0,4.5,1.106636e+09
3,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,15.0,2.5,1.510578e+09
4,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,17.0,4.5,1.305696e+09
...,...,...,...,...,...,...
100849,193581,Black Butler: Book of the Atlantic (2017),Action|Animation|Comedy|Fantasy,184.0,4.0,1.537109e+09
100850,193583,No Game No Life: Zero (2017),Animation|Comedy|Fantasy,184.0,3.5,1.537110e+09
100851,193585,Flint (2017),Drama,184.0,3.5,1.537110e+09
100852,193587,Bungo Stray Dogs: Dead Apple (2018),Action|Animation,184.0,3.5,1.537110e+09
100853,193609,Andrew Dice Clay: Dice Rules (1991),Comedy,331.0,4.0,1.537158e+09

In [40]:
t2=movies.merge(ratings,on='movieId',how='right')
t2

,movieId,title,genres,userId,rating,timestamp
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,1,4.0,964982703
1,3,Grumpier Old Men (1995),Comedy|Romance,1,4.0,964981247
2,6,Heat (1995),Action|Crime|Thriller,1,4.0,964982224
3,47,Seven (a.k.a. Se7en) (1995),Mystery|Thriller,1,5.0,964983815
4,50,"Usual Suspects, The (1995)",Crime|Mystery|Thriller,1,5.0,964982931
...,...,...,...,...,...,...
100831,166534,Split (2017),Drama|Horror|Thriller,610,4.0,1493848402
100832,168248,John Wick: Chapter Two (2017),Action|Crime|Thriller,610,5.0,1493850091
100833,168250,Get Out (2017),Horror,610,5.0,1494273047
100834,168252,Logan (2017),Action|Sci-Fi,610,5.0,1493846352
100835,170875,The Fate of the Furious (2017),Action|Crime|Drama|Thriller,610,3.0,1493846415

In [41]:
t3=movies.merge(ratings,on='movieId',how='outer')
t3

,movieId,title,genres,userId,rating,timestamp
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,1.0,4.0,9.649827e+08
1,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,5.0,4.0,8.474350e+08
2,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,7.0,4.5,1.106636e+09
3,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,15.0,2.5,1.510578e+09
4,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,17.0,4.5,1.305696e+09
...,...,...,...,...,...,...
100849,193581,Black Butler: Book of the Atlantic (2017),Action|Animation|Comedy|Fantasy,184.0,4.0,1.537109e+09
100850,193583,No Game No Life: Zero (2017),Animation|Comedy|Fantasy,184.0,3.5,1.537110e+09
100851,193585,Flint (2017),Drama,184.0,3.5,1.537110e+09
100852,193587,Bungo Stray Dogs: Dead Apple (2018),Action|Animation,184.0,3.5,1.537110e+09
100853,193609,Andrew Dice Clay: Dice Rules (1991),Comedy,331.0,4.0,1.537158e+09

In [43]:
avg_ratings=ratings.groupby('movieId').mean()
avg_ratings

             userId    rating     timestamp
movieId
1        306.530233  3.920930  1.129835e+09
2        329.554545  3.431818  1.135805e+09
3        283.596154  3.259615  1.005110e+09
4        219.857143  2.357143  8.985789e+08
5        299.571429  3.071429  9.926643e+08
...             ...       ...           ...
193581   184.000000  4.000000  1.537109e+09
193583   184.000000  3.500000  1.537110e+09
193585   184.000000  3.500000  1.537110e+09
193587   184.000000  3.500000  1.537110e+09
193609   331.000000  4.000000  1.537158e+09

[9724 rows x 3 columns]

In [46]:
box_office=movies.merge(avg_ratings,on='movieId',how='inner')
box_office.head()

,movieId,title,genres,userId,rating,timestamp
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,306.530233,3.920930,1.129835e+09
1,2,Jumanji (1995),Adventure|Children|Fantasy,329.554545,3.431818,1.135805e+09
2,3,Grumpier Old Men (1995),Comedy|Romance,283.596154,3.259615,1.005110e+09
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance,219.857143,2.357143,8.985789e+08
4,5,Father of the Bride Part II (1995),Comedy,299.571429,3.071429,9.926643e+08

In [50]:
is_highly_rated=box_office['rating']>=4.0

In [53]:
box_office[is_highly_rated]

,movieId,title,genres,userId,rating,timestamp
27,28,Persuasion (1995),Drama|Romance,382.636364,4.227273,1.162221e+09
28,29,"City of Lost Children, The (Cité des enfants p...",Adventure|Drama|Fantasy|Mystery|Sci-Fi,328.368421,4.013158,1.120213e+09
36,40,"Cry, the Beloved Country (1995)",Drama,427.500000,4.250000,9.542718e+08
46,50,"Usual Suspects, The (1995)",Crime|Mystery|Thriller,299.279412,4.237745,1.162501e+09
48,53,Lamerica (1994),Adventure|Drama,344.000000,5.000000,9.263241e+08
...,...,...,...,...,...,...
9713,191005,Gintama (2017),Action|Adventure|Comedy|Sci-Fi,184.000000,4.500000,1.537109e+09
9716,193571,Silver Spoon (2014),Comedy|Drama,184.000000,4.000000,1.537099e+09
9717,193573,Love Live! The School Idol Movie (2015),Animation,184.000000,4.000000,1.537100e+09
9719,193581,Black Butler: Book of the Atlantic (2017),Action|Animation|Comedy|Fantasy,184.000000,4.000000,1.537109e+09
9723,193609,Andrew Dice Clay: Dice Rules (1991),Comedy,331.000000,4.000000,1.537158e+09